# Generated by Django 4.2.3 on 2023-07-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_games_game'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
